name: Adfactor
favicon: null
layout_spectrum: 0.8195202557835728
typography_spectrum: 0.9782636822201312
title: Adfactor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1852108919993043
  lightness: 0.35163166117854416
  saturation: 0.8232922870665789
  rhythmicContrast: 0.9787223748862743
purpose: []
